name: rec_xiaomi_firmware_maker
description: Modern Xiaomi Firmware Creator with Payload.bin Support
version: 2.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Design
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10

  # File handling
  file_picker: ^8.1.2
  archive: ^3.6.1
  path_provider: ^2.1.4
  path: ^1.9.0

  # Process & Async
  process_run: ^1.2.0

  # State management
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
